x-postgres-variables: &postgres-variables
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

x-server-variables: &server-variables
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: ${DEBUG}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}


services:
  postgres:
    image: postgres:16.6
    container_name: postgres
    environment: *postgres-variables
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data  # do not use like: ./data:/var/lib/... it's definitely gonna throw an error
    
  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    ports:
      - "6377:6379"
    
  server:
    build:
      context: .
    container_name: server
    environment: *server-variables
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  data: # define "data" in postgres volumes